---

- name: "config: Create directories for Ansible Lint configuration"
  file:
    state: directory
    dest: "{{ item.path|dirname }}"
  loop: "{{ mal_config }}"

- name: "config: Configure Ansible Lint"
  template:
    src: "{{ item.template|default('ansible-lint-default.j2') }}"
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: "{{ mal_backup_conf }}"
  loop: "{{ mal_config }}"

# EOF
...
