---

- name: "github: Create directory for the source code {{ mal_github_dest }}"
  file:
    state: directory
    path: "{{ mal_github_dest }}"
  tags: mal_github_fetch

- name: "github: Download {{ mal_github_url }}/{{ mal_github_file }}"
  get_url:
    url: "{{ mal_github_url }}/{{ mal_github_file }}"
    dest: "{{ mal_github_dest }}/ansible-lint-{{ mal_github_file }}"
    checksum: "{{ mal_github_checksum }}"
  tags: mal_github_fetch

- name: "github: Check existence of {{ mal_github_dest }}/ansible-lint-{{
                                       mal_github_file }}"
  stat:
    path: "{{ mal_github_dest }}/ansible-lint-{{ mal_github_file }}"
  register: mal_github_fetched
  tags: mal_github_extract

- name: "github: Debug mal_github_fetched"
  debug:
    var: mal_github_fetched.stat.checksum
  when: mal_debug
  tags: mal_github_extract

- name: "github: Extract sources to {{ mal_github_dest }}"
  unarchive:
    src: "{{ mal_github_dest }}/ansible-lint-{{ mal_github_file }}"
    dest: "{{ mal_github_dest }}"
    remote_src: true
  when: mal_github_fetched.stat.exists
  tags: mal_github_extract

- name: "github: Create symbolic links"
  file:
    state: link
    src: "{{ mal_github_dest }}/{{ mal_github_dir }}"
    dest: "{{ mal_github_dest }}/ansible-lint"
    force: true
  tags: mal_github_link

- name: "github: Install with pip"
  pip:
    name: "{{ mal_github_dest }}/ansible-lint-{{ mal_github_file }}"
    executable: "{{ mal_pip_executable }}"
  when: mal_github_fetched.stat.exists
  tags: mal_github_install

# EOF
...
