---

- name: "links: Create directories for links"
  ansible.builtin.file:
    state: directory
    dest: "{{ item.dest|dirname }}"
  loop: "{{ mal_links }}"
  loop_control:
    label: "{{ item.dest|dirname }}"

- name: "links: Create links"
  ansible.builtin.file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force|default(false) }}"
  loop: "{{ mal_links }}"

# EOF
...
