---

- name: "packages: Install Ansible Lint packages FreeBSD"
  pkgng:
    name: "{{ mal_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"

- name: "packages: Install Ansible Lint ports FreeBSD"
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ mal_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"

- name: "packages: Install Ansible Lint packages Linux"
  package:
    name: "{{ item }}"
  loop: "{{ mal_packages }}"
  register: result
  retries: "{{ linux_install_retries }}"
  until: result is succeeded
  delay: "{{ linux_install_delay }}"
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "RedHat")

# EOF
...
