---

# FreeBSD
- name: "packages: Install Ansible Lint packages FreeBSD"
  pkgng:
    name: "{{ item.name }}"
  loop: "{{ mal_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"

- name: "packages: Install Ansible Lint ports FreeBSD"
  portinstall:
    name: "{{ item.name }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ mal_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"

# Linux
- name: "packages: Install Ansible Lint packages Linux"
  when: ansible_os_family == "RedHat"
  package:
    name: "{{ item.name }}"
  loop: "{{ mal_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ linux_install_retries }}"
  delay: "{{ linux_install_delay }}"

# pip
- name: "packages: Test {{ mal_pip_executable }} exists"
  block:
    - name: "packages: Stat {{ mal_pip_executable }}"
      stat:
        path: "{{ mal_pip_executable }}"
      register: result
    - name: "packages: Not exists {{ mal_pip_executable }}"
      when: not result.stat.exists
      debug:
        msg: "[ERROR] {{ mal_pip_executable }} does not exist. End of host."
    - name: "packages: Meta end host"
      when: not result.stat.exists
      meta: end_host
  when: ansible_os_family == "Debian"

- name: "packages: Install Ansible Lint pip packages for {{ mal_owner }}"
  become_user: "{{ mal_owner }}"
  become: true
  changed_when: false  # Note 1.
  pip:
    name: "{{ item.name }}"
    executable: "{{ mal_pip_executable }}"
    version: "{{ item.version|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    extra_args: "{{ pip_extraagrs|default(omit) }}"
  loop: "{{ mal_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ pip_install_retries }}"
  delay: "{{ pip_install_delay }}"
  when: ansible_os_family == "Debian"

- name: "packages: Debug pip packages"
  when: mal_debug|bool
  debug:
    var: result

- name: "packages: Install Ansible Lint pip requirements for {{ mal_owner }}"
  become_user: "{{ mal_owner }}"
  become: true
  changed_when: false  # Note 1.
  pip:
    requirements: "{{ mal_pip_requirements|default(omit) }}"
    executable: "{{ mal_pip_executable }}"
    extra_args: "{{ pip_extraagrs|default(omit) }}"
  register: result
  until: result is succeeded
  retries: "{{ pip_install_retries }}"
  delay: "{{ pip_install_delay }}"
  when:
    - ansible_os_family == "Debian"
    - pip_requirements is defined

- name: "packages: Debug pip requirements"
  when: mal_debug|bool
  debug:
    var: result

# Note 1.
# The pip module isn't always idempotent #28952
# https://github.com/ansible/ansible/issues/28952

# EOF
...
